#!/bin/sh
# Test
if [ ! $2 ]
then
	echo "usage: $0 method uri"
	echo "sample: $0 GET /test.htm"
	exit 1
fi
CMD="$1 $2 HTTP/1.1
Connection: close

"
echo $CMD
echo
printf "$CMD" | nc 192.168.1.13 8080
echo
